baseURL: https://dev.progettodighe.it/main
title: ProgettoDighe

languageCode: it-it
defaultContentLanguage: it

enableEmoji: true
enableGitInfo: true
enableRobotsTXT: true
canonifyURLs: true
pluralizelisttitles: false

params:
    description: Il punto di riferimento per gli appassionati di dighe, centrali idroelettriche e opere idrauliche.
    images:
    webmaster: Elvis Del Tedesco
    webmasterMail: info@progettodighe.it
    disqusShortname: progettodighe
theme: ananke

outputs:
  section:
  - html
  - rss
  - json