baseURL: https://www.progettodighe.it/
title: ProgettoDighe
params:
  webmaster: "Elvis Del Tedesco"
  webmasterMail: "info@progettodighe.it"
  description: Il punto di riferimento per gli appassionati di dighe, centrali idroelettriche e opere idrauliche.
languageCode: it
theme: ananke
enableGitInfo: true
enableRobotsTXT: true
pluralizelisttitles: false
